import './globals.css'
// import Head from 'next/head'


export const metadata = {
  title: 'AUV',
  description: 'Generated by create next app',
  image:""
}

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
    <head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
      <meta property="image" content={metadata.image} />
    </head>
    <body className='h-[2000px]'>
      {children}
    {/* <Footer/> */}
      </body>
  </html>
  )
}
